version: '3.8'

services:
  db:
    image: postgres:16 # You can specify a different version like 14, 15, etc.
    restart: always
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: course     # Replace with your desired username
      POSTGRES_PASSWORD: changeme # Replace with a strong password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    

volumes:
  pgdata: